# Generated by Django 5.0 on 2024-04-28 03:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_role'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
