# Generated by Django 5.0 on 2024-04-29 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_department_eventapplication'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='google_calendar_credentials',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
